import sys
import os
import threading
import requests
import streamlit as st
import uvicorn

# Make project root importable
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from api.main import app as fastapi_app


# -----------------------------
# Run FastAPI in background
# -----------------------------
def run_fastapi():
    uvicorn.run(
        fastapi_app,
        host="0.0.0.0",
        port=8000,
        log_level="warning"
    )


if "fastapi_started" not in st.session_state:
    threading.Thread(target=run_fastapi, daemon=True).start()
    st.session_state["fastapi_started"] = True


# -----------------------------
# FastAPI endpoint
# -----------------------------
API_URL = "http://127.0.0.1:8000/generate"


# -----------------------------
# Streamlit Page Config
# -----------------------------
st.set_page_config(
    page_title="GRPO-Fine-Tuned SmolLM2 Demo",
    page_icon="🚀",
    layout="centered"
)


# -----------------------------
# UI Header
# -----------------------------
st.title("🚀 GRPO-Fine-Tuned SmolLM2")
st.write(
    "This demo showcases a **SmolLM2-135M** model fine-tuned using "
    "**Group Relative Policy Optimization (GRPO)** with **LoRA** for "
    "parameter-efficient training."
)


# -----------------------------
# Prompt Input
# -----------------------------
prompt = st.text_area(
    "Enter your prompt",
    placeholder="Paste a long document, question, or any prompt here...",
    height=250
)


# -----------------------------
# Generation Controls
# -----------------------------
max_tokens = st.slider(
    "Max New Tokens",
    min_value=10,
    max_value=96,
    value=96,
    help="Controls the maximum number of tokens generated by the model."
)


# -----------------------------
# Generate Button
# -----------------------------
if st.button("Generate Response"):
    if prompt.strip() == "":
        st.warning("Please enter a prompt.")
    else:
        try:
            with st.spinner("Generating response..."):
                response = requests.post(
                    API_URL,
                    json={
                        "prompt": prompt,
                        "max_new_tokens": max_tokens
                    },
                    timeout=30
                )

            if response.status_code == 200:
                result = response.json()
                generated_text = result.get("generated_text", "")

                if generated_text:
                    st.subheader("Model Response")
                    st.success(generated_text)
                    st.caption(f"Length: {len(generated_text)} characters")
                else:
                    st.info("The model did not generate a response.")

            else:
                st.error(
                    f"API Error: {response.json().get('detail', 'Unknown error')}"
                )

        except requests.exceptions.RequestException as e:
            st.error(f"❌ Could not connect to the FastAPI server: {e}")
